[book]
authors = ["Junior Sundar"]
language = "en"
src = "src"
title = "OxMPL Documentation"

[output.html]
git-repository-url = "https://github.com/juniorsundar/oxmpl"
edit-url-template = "https://github.com/juniorsundar/oxmpl/edit/main/docs/{path}"
mathjax-support = true
